DROP TABLE IF EXISTS todo;

DROP TABLE IF EXISTS tag;

DROP TABLE IF EXISTS note;

DROP TABLE IF EXISTS item;

CREATE TABLE tag (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT UNIQUE NOT NULL,
    color TEXT NOT NULL
);

CREATE TABLE note (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    createdAt TEXT NOT NULL,
    tag_id INTEGER,
    FOREIGN KEY (tag_id) REFERENCES tag (id)
);

CREATE TABLE todo (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    createdAt TEXT NOT NULL
);

CREATE TABLE item (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    todo_id INTEGER NOT NULL,
    FOREIGN KEY (todo_id) REFERENCES todo (id)
);
